# Generated by Django 4.2.3 on 2023-08-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='pdf_file',
            new_name='file',
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
